### ISSUE TITLE
We need cell selection

### ISSUE THREAD

**Issue by Mango3403** [infinite-table/infinite-react#120]
## Description
Hi, I recently study and use the component on my formal project. There is a question how can I use the `cellSelection` and `onCellSelectionChange`. I try to call it like `rowSelection`, but nothing happened. Any helps?

## How do I use it
![image](https://user-images.githubusercontent.com/20784705/187817170-e2d17e23-d753-4be8-b880-6feac4ffe00c.png)

## Env
- Windows 10
- react ^17.0.0
- @infinite-table/infinite-react ^0.4.8

**Comment by roblotter** [comment]
As per our documentation on cell selection https://infinite-table.com/docs/latest/learn/selection/cell-selection
it's a feature that will be implemented soon. We just finished implementing row selection and will start working on cell selection as well.
For now, you can use cell navigation only.

**Comment by radubrehar** [comment]
We now fully support cell selection in `3.0.0`

**Comment by radubrehar** [comment]
@Mango3403 cell selection support is out! Give it a try and let us know if it solves your problem.
