### ISSUE TITLE
onScrollToBottom (=getNextPage) is not called when scrollbar is not displayed

### ISSUE THREAD

**Issue by vitolpoc** [infinite-table/infinite-react#14]
When rendering, if the grid’s set pageSize allows showing a number of rows smaller than the viewport, then grids should automatically know to call and get the nextPage to fill the remaining if more data exists.
The current property named onScrollToBottom is not being called if there is no scrollbar but there is more data available.

https://codesandbox.io/s/sandpack-project-forked-csv91?file=/src/App.tsx

**Comment by roblotter** [comment]
Fixed in `0.0.9`

**Comment by roblotter** [comment]
See updated docs on live pagination https://infinite-table.com/docs/latest/learn/working-with-data/live-pagination
