### ISSUE TITLE
Improve docs on sorting

### ISSUE THREAD

**Issue by radubrehar** [infinite-table/infinite-react#152]
Make it clear that custom sort functions (in custom sort types) only need to sort data in ASC order

**Comment by roblotter** [comment]
Also add documentation on `sortFunction`

**Comment by roblotter** [comment]
See 
https://infinite-table.com/docs/learn/working-with-data/sorting#understanding-sort-mode
and
https://infinite-table.com/docs/reference/datasource-props#sortFunction
