### ISSUE TITLE
Add support for functions to InfiniteTableColumn.align 

### ISSUE THREAD

**Issue by andreifloricel** [infinite-table/infinite-react#155]
For InfiniteTableColumn.<[align | headerAlign | verticalAlign](https://github.com/infinite-table/infinite-react/blob/935c04cfac5aa2857fe913f05cfe942956f645d0/source/src/components/InfiniteTable/types/InfiniteTableColumn.ts#L396)> properties
(analog [InfiniteTableColumn.style](https://github.com/infinite-table/infinite-react/blob/935c04cfac5aa2857fe913f05cfe942956f645d0/source/src/components/InfiniteTable/types/InfiniteTableColumn.ts#L411))

**Comment by bogdanpetru** [comment]
And `verticalAlign` please :).
