### ISSUE TITLE
"cannot find column at index" logs in the console

### ISSUE THREAD

**Issue by vitolpoc** [infinite-table/infinite-react#16]
When using pivot configuration, there are some console.log that let us think there are errors: "cannot find column at index".

To reproduce and see the logs, fork the first example in the following documentation page and open the console to see the messages:
https://infinite-table.com/docs/latest/learn/grouping-and-pivoting/pivoting

**Comment by roblotter** [comment]
Thanks - will be fixed in `0.0.10` (due shortly, as we just released `0.0.9`)
