### ISSUE TITLE
Add support for "multi-column" and "inline" groupRenderStrategy when used as pivot

### ISSUE THREAD

**Issue by vitolpoc** [infinite-table/infinite-react#17]
When using pivot, the only `groupRenderStrategy` available is `single-column`, please add support for `multi-column` and `inline` strategies as well.

In the following code sandbox, `inline` mode has been set, the default group row state has been set to expand the first node. Notice the groups are displayed as a tree and the expanded node ("TypeScript") is not visible.
https://codesandbox.io/s/sandpack-project-forked-zgml8?file=/src/App.tsx

**Comment by roblotter** [comment]
<img width="926" alt="Screenshot 2022-01-31 at 14 39 32" src="https://user-images.githubusercontent.com/50020244/151795271-c6eff94b-729f-4508-a5ca-065259cda2a8.png">
source: https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/RunningTotals/jQuery/Light/

**Comment by roblotter** [comment]
This would be a nice addition to "inline" group rendering strategy - to have a way (a config prop) to render both what we have now or render group row separately and all other rows belonging to the group as a separate merged cell

**Comment by roblotter** [comment]
Shipped in `0.2.3`
