### ISSUE TITLE
Enhance multi column sort usability

### ISSUE THREAD

**Issue by andreifloricel** [infinite-table/infinite-react#172]
Multi column sorting is not intuitive because the user has to explicitly click on each header to remove the sorting.

Multisort could probably be changed to work with an additional control key (ctrl + click).

**Comment by roblotter** [comment]
We've implemented `multiSortBehavior` as a prop on the `InfiniteTable` component (so not on `DataSouce`) - included in v `1.3.7`

The two possible values are:
 - `replace` - the default
 - `append`

So your suggested behaviour is now the default one. Thanks for contributing!
