### ISSUE TITLE
Column Menu Sorting is not working as expected

### ISSUE THREAD

**Issue by andreifloricel** [infinite-table/infinite-react#173]
Nothing happens when clicking on 'Sort Ascending'/'Sort Descending' column menu items.
The sort itself works when actioned by header clicks.

**Comment by radubrehar** [comment]
Indeed, seems like this is not working

https://codesandbox.io/s/adoring-snow-fpzlr4

which is the example on this paragraph https://infinite-table.com/docs/learn/sorting/single-sorting#multiple-sorting

**Comment by roblotter** [comment]
Thanks for reporting @andreifloricel !

This should now be fixed in v `1.3.7` that was just published
