### ISSUE TITLE
Resetting pivot configuration is not working

### ISSUE THREAD

**Issue by vitolpoc** [infinite-table/infinite-react#18]
Switching from a "no pivot" configuration to a "pivot" configuration is working but not in the other way.

The following sandbox illustrates the issue
- the initial state is a "no pivot" configuration
- click on the button "1. Pivot": works as expected
- click on the button "2. No Pivot" that basically set the pivotBy to undefined: does not change the table status

https://codesandbox.io/s/infinite-table-pivot-no-pivot-switch-wb95t?file=/src/App.tsx

**Comment by roblotter** [comment]
Fixed in `0.1.0`
