### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by yeasin-hossain** [infinite-table/infinite-react#195]
**Describe the bug**
<img width="924" alt="image" src="https://github.com/infinite-table/infinite-react/assets/50882838/5431d52e-d58a-42ae-9fb4-bf05bad88ff3">

**Codesandbox demo**

A link to a fully working https://codesandbox.io/ demo that reproduces the issue.
You can use this [starter template](https://codesandbox.io/s/serverless-framework-gxs1fb?file=/App.tsx).

**To Reproduce**

Steps to reproduce the behavior (in the codesandbox above):
1. Click on '....'
2. Scroll down to '....'
3. See error

**Expected behavior**

**Screenshots**
<img width="924" alt="image" src="https://github.com/infinite-table/infinite-react/assets/50882838/cc566539-0b59-4c1a-be89-34e169618015">

**Platforms**

 - Infinite Table Version [2.0.4]
 - Browser [chrome]
 - OS: [MacOS]

**Additional context**
my react version "react": "^17.0.2",

**Comment by roblotter** [comment]
hi @yeasin-hossain 

Have you tried the demo on our website?
Please see our https://infinite-table.com/docs/learn/getting-started page and fork the example there to get up & running quickly.

Can you provide a link to a broken codesandbox? Would help us if you provide a minimal repro.

Thanks 🙌

**Comment by roblotter** [comment]
Closing as we have no feedback for 2 weeks.
If you feel it's a real problem, please open a more specific and detailed issue. Thank you.
