### ISSUE TITLE
Sorting / Draggable Bug

### ISSUE THREAD

**Issue by sammyhajomar** [infinite-table/infinite-react#221]
When I have `draggableColumns` set to false and `sortable` set to false in my `<InfiniteTable>` sorting still occurs when you press on the column header. Only when I remove `draggableColumns` or set it to `true` it will disable sorting. I made sure the column specific overriding `defaultSortable` is not being utilized

I'm on version 3.2.10 and I'm using MacOS. The behavior is the same across different browsers.

A remake of the issue: https://codesandbox.io/p/devbox/infinite-table-nsj4hk

**Comment by radubrehar** [comment]
Thanks for the report - we're checking and coming back with a fix!

**Comment by radubrehar** [comment]
Thanks @sammyhajomar for the bug report! 
Should be fixed now in 3.2.11, which has just been published.

Let us know if you have any other issues - happy to help!
