### ISSUE TITLE
Display issue with groups and pivot

### ISSUE THREAD

**Issue by vitolpoc** [infinite-table/infinite-react#42]
version: 0.2.6

Steps to reproduce:
- On the documentation sample available here: https://infinite-table.com/docs/latest/learn/working-with-data/lazy-loading#server-side-pivoting-with-lazy-load
- scroll horizontally
- expand or collapse a group
- => data are not displayed anymore

Simply scroll again to see the data again
![image](https://user-images.githubusercontent.com/42170298/154430156-0b8db14f-e3d1-4dda-a473-5714d215b69e.png)

**Comment by roblotter** [comment]
We were able to reproduce the issue and also get to the code that's causing it, so we're preparing a fix that we'll release today
